platform :ios, '10.0'


target 'Example' do
  use_frameworks!

  pod 'InPlayerSDK', :git => 'https://github.com/inplayer-org/inplayer-ios-sdk.git'

  target 'ExampleTests' do
    inherit! :search_paths
  end
  
end
