platform :ios, '10.0'

target 'InPlayerSDKExample-iOS' do
  use_frameworks!

  pod 'SwiftKeychainWrapper'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'

  target 'InPlayerSDKExample-iOSTests' do
    inherit! :search_paths
  end

end
